version: "3"
services:
  app:
    build: .
    ports:
      - "8080:80"
    env_file:
      - ./docker/env
    volumes:
<<<<<<< HEAD
      -./app/public:/srv/app/public
=======
      - ./app/public:/srv/app/public
>>>>>>> upstream/red-10-07
